name: enram
dependencies:
- blas=1.1=openblas
- boto3=1.4.3=py35_0
- botocore=1.4.90=py35_0
- cairo=1.14.6=0
- certifi=2016.9.26=py35_0
- decorator=4.0.10=py35_1
- docutils=0.13.1=py35_0
- entrypoints=0.2.2=py35_0
- falcon=1.0.0=py35_0
- fontconfig=2.11.1=6
- freetype=2.6.3=1
- gettext=0.19.7=1
- glib=2.51.0=2
- h5py=2.6.0=np111py35_7
- harfbuzz=1.3.4=0
- hdf5=1.8.17=9
- hug=2.2.0=py35_0
- icu=56.1=4
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_2
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_2
- jinja2=2.8.1=py35_0
- jmespath=0.9.0=py35_0
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- libffi=3.2.1=3
- libgfortran=3.0.0=1
- libiconv=1.14=4
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- libxml2=2.9.4=3
- markupsafe=0.23=py35_2
- mistune=0.7.3=py35_0
- mkl=2017.0.1=0
- nbconvert=4.2.0=py35_0
- nbformat=4.2.0=py35_0
- ncurses=5.9=10
- notebook=4.3.1=py35_0
- numexpr=2.6.1=np111py35_2
- numpy=1.11.3=py35_blas_openblas_200
- openblas=0.2.19=0
- openssl=1.0.2j=0
- pandas=0.19.2=np111py35_1
- pango=1.40.3=0
- path.py=10.0=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- py=1.4.32=py35_0
- pygments=2.1.3=py35_1
- pyqt=4.11.4=py35_4
- pytables=3.3.0=np111py35_0
- pytest=3.0.6=py35_0
- python=3.5.3=0
- python-dateutil=2.6.0=py35_0
- python-mimeparse=1.5.2=py35_0
- pytz=2016.10=py35_0
- pyzmq=16.0.2=py35_0
- qt=4.8.7=3
- qtconsole=4.2.1=py35_1
- readline=6.2=2
- requests=2.12.4=py35_0
- s3transfer=0.1.10=py35_0
- setuptools=32.3.1=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_1
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- terminado=0.6=py35_0
- tk=8.5.19=1
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- uwsgi=2.0.12=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_3
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
  - tables==3.3.0

